name: first ghithib Actions 
on: push

jobs:
  my_first_job:
    runs-on: ubuntu-latest

    steps:
      - name: messgae
        run: echo "succ3essfullly  creaate cicd yaml file for GHA"
      
    
