name: this is first githib action concurrency
on: push

jobs:
  my_fisrs_job:
    runs-on: ubuntu-latest

    steps:
      - name: message
        run : echo "this is my fist yaml file for gha"

   
      
    
