name: Its for self-hosted Runners
on: push

jobs:
  MY-SELF-HOSTED:
    runs-on: self-hosted

    steps:
      - name: sample message
        run: echo "I am using for self-hosted runners from the second branch"
